import { Grid } from "semantic-ui-react";
import HottestStats from "../components/stats-page/global/hottest-stats";
import CheapestnMostExpensiveProducts from "../components/stats-page/global/cheap-or-expensive-global";
import CheapestnMostExpensiveProductsPersonal from "../components/stats-page/personal/cheap-or-expensive-personal";
import MostLikedProducts from "../components/stats-page/global/most-liked-products";
import MostBought from "../components/stats-page/personal/most-bought";

import "./stats-page.css";

const globalStats = {
  "Global Statistics": {
    "Cheapest Products": [
      {
        category: "Consoles",
        desc: "It's worth mentioning that there's nothing inherently wrong with cheap handheld emulators. Hit em with the supersized shirts and the SOOOUUULJAAAA BOOYYYYYYY",
        id: 43,
        name: "Soulja Boy handheld",
        price: "0.01",
        stock: 3,
        visible: true,
      },
      {
        category: "Consoles",
        desc: "They call me Houdini",
        id: 114,
        name: "Product1",
        price: "0.02",
        stock: 0,
        visible: true,
      },
      {
        category: "Consoles",
        desc: "They call me Houdini",
        id: 144,
        name: "Product1",
        price: "0.02",
        stock: 0,
        visible: true,
      },
      {
        category: "Storage",
        desc: "Surprised you still need this",
        id: 121,
        name: "CD",
        price: "10",
        stock: 617,
        visible: true,
      },
      {
        category: "Storage",
        desc: "No way you can still use this",
        id: 122,
        name: "Floppy Disc",
        price: "15",
        stock: 56,
        visible: true,
      },
      {
        category: "Storage",
        desc: "Generic USB Drive 1GB",
        id: 118,
        name: "USB Drive 1GB",
        price: "20",
        stock: 74,
        visible: true,
      },
      {
        category: "Peripherals",
        desc: "Slithers on your mousepad",
        id: 70,
        name: "Razer Basilisk V3 Mouse",
        price: "22.22",
        stock: 10,
        visible: true,
      },
      {
        category: "Controllers",
        desc: "A revolution for controllers",
        id: 88,
        name: "DualSense 2",
        price: "25",
        stock: 45,
        visible: true,
      },
      {
        category: "Controllers",
        desc: "Its like a TV remote",
        id: 89,
        name: "Wii Remote",
        price: "25",
        stock: 98,
        visible: true,
      },
      {
        category: "Gift Cards",
        desc: "Customizable value gift card",
        id: 140,
        name: "Lowes",
        price: "25",
        stock: 150,
        visible: true,
      },
    ],
    "Hottest Categories": [
      {
        name: "Storage",
        quantity_bought: 76,
      },
      {
        name: "Gift Cards",
        quantity_bought: 60,
      },
      {
        name: "Consoles",
        quantity_bought: 9,
      },
      {
        name: "PC",
        quantity_bought: 2,
      },
    ],
    "Hottest Products": [
      {
        category: "Storage",
        desc: "Generic USB Drive 1GB",
        id: 118,
        name: "USB Drive 1GB",
        price: "20",
        stock: 74,
        visible: true,
      },
      {
        category: "Gift Cards",
        desc: "Customizable value gift card",
        id: 141,
        name: "Apple",
        price: "25",
        stock: 2670,
        visible: true,
      },
      {
        category: "Consoles",
        desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
        id: 39,
        name: "PlayStation 4",
        price: "359.99",
        stock: 25,
        visible: true,
      },
      {
        category: "Storage",
        desc: "Surprised you still need this",
        id: 121,
        name: "CD",
        price: "10",
        stock: 617,
        visible: true,
      },
      {
        category: "PC",
        desc: "Its good for gaming",
        id: 106,
        name: "AMD Ryzen 5",
        price: "199",
        stock: 978,
        visible: true,
      },
    ],
    "Most Expensive Products": [
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 152,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: true,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 150,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: false,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 149,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: false,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 153,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: false,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 148,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: false,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 154,
        name: "Keyboard2",
        price: "1999.99",
        stock: 1,
        visible: true,
      },
      {
        category: "Peripherals",
        desc: "The fanciest keyboard youve ever seen!",
        id: 147,
        name: "Keyboard",
        price: "1999.99",
        stock: 0,
        visible: true,
      },
      {
        category: "Smartphones",
        desc: "Bad luck iPhone",
        id: 80,
        name: "iPhone 13",
        price: "1300",
        stock: 43,
        visible: true,
      },
      {
        category: "Smartphones",
        desc: "1 + 2 = 12",
        id: 79,
        name: "iPhone 12",
        price: "1200",
        stock: 46,
        visible: true,
      },
      {
        category: "Smartphones",
        desc: "So we back to normal numbers I guess",
        id: 78,
        name: "iPhone 11",
        price: "1100",
        stock: 208,
        visible: true,
      },
    ],
    "Most Liked Products": [
      {
        category: "Controllers",
        desc: "Take control of your games 360 days a year...",
        id: 86,
        name: "Xbox 360 Controller",
        price: "36",
        quantity: 50,
        visible: true,
      },
      {
        category: "Storage",
        desc: "Surprised you still need this",
        id: 121,
        name: "CD",
        price: "10",
        quantity: 617,
        visible: true,
      },
      {
        category: "Peripherals",
        desc: "Really hot keyboard right now",
        id: 63,
        name: "Roccat Magma Keyboard",
        price: "60",
        quantity: 132,
        visible: true,
      },
    ],
  },
  Products: [
    {
      category: "Consoles",
      desc: "Xbox One Console. You want it, we got it. Get your own XBOX and forget boredom.",
      id: 40,
      name: "Xbox One",
      price: "299.99",
      stock: 1000000000,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "It's worth mentioning that there's nothing inherently wrong with cheap handheld emulators. Hit em with the supersized shirts and the SOOOUUULJAAAA BOOYYYYYYY",
      id: 43,
      name: "Soulja Boy handheld",
      price: "0.01",
      stock: 3,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "Im pretty good?",
      id: 46,
      name: "Xbox Series X",
      price: "549.99",
      stock: 32,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "Want to have the best childhood ever? Get me!",
      id: 48,
      name: "DSi",
      price: "149.99",
      stock: 43,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Bring back the old games",
      id: 54,
      name: "Battlefield",
      price: "42.2",
      stock: 653,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "You will cry at the end",
      id: 56,
      name: "Red Dead Redemption ",
      price: "129.99",
      stock: 67533,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "The good kind of bad. Not fun. ",
      id: 57,
      name: "Death Stranding",
      price: "111.11",
      stock: 53,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Samurai dress up",
      id: 59,
      name: "Ghost of Tsushima",
      price: "99.99",
      stock: 34,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Parkour sim",
      id: 60,
      name: "Dying Light 2",
      price: "80.08",
      stock: 6,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "RGB Gaming Keyboard",
      id: 62,
      name: "Corsair K95 Keyboard",
      price: "50",
      stock: 152,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "The logical choice for a mouse",
      id: 67,
      name: "Logitech G203 Mouse",
      price: "59.99",
      stock: 46,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Stone cold accuracy",
      id: 68,
      name: "Razer Naga Pro Mouse",
      price: "39.99",
      stock: 58,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "BOY!",
      id: 58,
      name: "God of War",
      price: "80",
      stock: 15,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "They call me Houdini",
      id: 45,
      name: "Playstation 2",
      price: "169.99",
      stock: 0,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Robot dinosaurs",
      id: 49,
      name: "Horizon: Forbidden ",
      price: "45",
      stock: 54,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Cannot be returned",
      id: 52,
      name: "Returnal",
      price: "129.99",
      stock: 63,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Release the audio",
      id: 101,
      name: "Razer Kraken X (Black)",
      price: "59.99",
      stock: 88,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "It's a Wii. You know you want to play tennis and break your screen :D",
      id: 41,
      name: "Nintendo Wii",
      price: "75",
      stock: 148,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
      id: 39,
      name: "PlayStation 4",
      price: "359.99",
      stock: 25,
      visible: true,
    },
    {
      category: "Consoles",
      desc: 'Tired of all of your friends telling you to go play "Breath of the Wild"? Succumb to peer pressure!',
      id: 42,
      name: "Nintendo Switch",
      price: "299.99",
      stock: 83,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "A Portable Play Station??? What will they think of next?",
      id: 47,
      name: "PlayStation Portable",
      price: "249.99",
      stock: 41,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "Its like a game, but in a cube!!!",
      id: 44,
      name: "Nintendo GameCube",
      price: "199",
      stock: 87,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Like the S6 but better",
      id: 72,
      name: "Samsung Galaxy S7",
      price: "700",
      stock: 132,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Like the S7 but better",
      id: 73,
      name: "Samsung Galaxy S8",
      price: "800",
      stock: 456,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Like the S8 but better",
      id: 74,
      name: "Samsung Galaxy S9",
      price: "900",
      stock: 84,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Like the S9 but better",
      id: 75,
      name: "Samsung Galaxy S10",
      price: "1000",
      stock: 35,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Its an iPhone so yeah",
      id: 76,
      name: "iPhone 8",
      price: "800",
      stock: 641,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "They skipped the iPhone 9 smh",
      id: 77,
      name: "iPhone X",
      price: "1000",
      stock: 301,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "So we back to normal numbers I guess",
      id: 78,
      name: "iPhone 11",
      price: "1100",
      stock: 208,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "1 + 2 = 12",
      id: 79,
      name: "iPhone 12",
      price: "1200",
      stock: 46,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Bad luck iPhone",
      id: 80,
      name: "iPhone 13",
      price: "1300",
      stock: 43,
      visible: true,
    },
    {
      category: "Smartphones",
      desc: "Now available in Adamantium Silver",
      id: 81,
      name: "Nokia 3310",
      price: "33.1",
      stock: 800,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Can't have anything good in Detroit",
      id: 53,
      name: "Detroit: Become Human",
      price: "49.99",
      stock: 89,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "The logical choice for a keyboard",
      id: 64,
      name: "Logitech G915 Keyboard",
      price: "45",
      stock: 18,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Slithers on your mousepad",
      id: 70,
      name: "Razer Basilisk V3 Mouse",
      price: "22.22",
      stock: 10,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Sharpest keyboard on the market",
      id: 65,
      name: "Razer BlackWidow Keyboard",
      price: "68.99",
      stock: 33,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Sturdy as steel",
      id: 69,
      name: "SteelSeries Prime Wireless Keyboard",
      price: "33.33",
      stock: 11,
      visible: true,
    },
    {
      category: "Video Games",
      desc: '"What kind of cop are you?" "A drunk one."',
      id: 50,
      name: "Disco Elysium: Final Cut",
      price: "52",
      stock: 4,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "Wait, this isn't a superman game",
      id: 51,
      name: "The Witcher 3: Wild Hunt",
      price: "69",
      stock: 7,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Get extra kills in game",
      id: 66,
      name: "Razer DeathAdder Mouse",
      price: "70",
      stock: 99,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Master the game",
      id: 71,
      name: "SteelSeries Sensei 310",
      price: "44.99",
      stock: 5,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "Really hot keyboard right now",
      id: 63,
      name: "Roccat Magma Keyboard",
      price: "60",
      stock: 132,
      visible: true,
    },
    {
      category: "Video Games",
      desc: "It said final, why are there 7?????",
      id: 55,
      name: "Final Fantasy VII Remake",
      price: "77.77",
      stock: 643,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "The beloved PlayStation 3 controller",
      id: 83,
      name: "Dualshock 3",
      price: "49.99",
      stock: 20,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "The much better PlayStation 4 controller",
      id: 84,
      name: "Dualshock 4",
      price: "69.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "Haptic feedback everywhere",
      id: 85,
      name: "DualSense",
      price: "79.99",
      stock: 40,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "Take control of your games 360 days a year...",
      id: 86,
      name: "Xbox 360 Controller",
      price: "36",
      stock: 50,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "One controller for the one",
      id: 87,
      name: "Xbox One Controller",
      price: "79.99",
      stock: 55,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "A revolution for controllers",
      id: 88,
      name: "DualSense 2",
      price: "25",
      stock: 45,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "Its like a TV remote",
      id: 89,
      name: "Wii Remote",
      price: "25",
      stock: 98,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "Drifting through the competition",
      id: 90,
      name: "Joy-Con",
      price: "39.99",
      stock: 46,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "For the nostalgia of arcade cabinets",
      id: 91,
      name: "Mad Catz Fightstick SFV Edition",
      price: "80",
      stock: 82,
      visible: true,
    },
    {
      category: "Controllers",
      desc: "For the modern fighting gamer",
      id: 92,
      name: "Qanba Drone Fightstick",
      price: "69.99",
      stock: 14,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Release the audio",
      id: 97,
      name: "Razer Kraken X (Blue)",
      price: "59.99",
      stock: 33,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Sharpest headset on the market now in black",
      id: 99,
      name: "Razer BlackShark V2 (Black)",
      price: "79.99",
      stock: 50,
      visible: true,
    },
    {
      category: "Audio",
      desc: "RGB Audio",
      id: 102,
      name: "CORSAIR VOID RGB ELITE",
      price: "80.00",
      stock: 11,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Release the audio",
      id: 100,
      name: "Razer Kraken X (Green)",
      price: "59.99",
      stock: 66,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "They call me Houdini2",
      id: 82,
      name: "Playstation 52",
      price: "169.99",
      stock: 0,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "The fanciest keyboard youve ever seen!",
      id: 152,
      name: "Keyboard2",
      price: "1999.99",
      stock: 1,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "The fanciest keyboard youve ever seen!",
      id: 154,
      name: "Keyboard2",
      price: "1999.99",
      stock: 1,
      visible: true,
    },
    {
      category: "Storage",
      desc: "4K HD movies of your cat",
      id: 113,
      name: "Blu-ray",
      price: "25",
      stock: 44,
      visible: true,
    },
    {
      category: "Storage",
      desc: "A Samsung SSD with 4TB capacity",
      id: 116,
      name: "Samsung SSD 4TB",
      price: "250",
      stock: 821,
      visible: true,
    },
    {
      category: "Storage",
      desc: "Generic USB Drive 1TB that's a lot of storage",
      id: 117,
      name: "USB Drive 1TB",
      price: "125",
      stock: 234,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 126,
      name: "Donkey Kong Amiibo",
      price: "29.99",
      stock: 15,
      visible: true,
    },
    {
      category: "PC",
      desc: "CPU for your PC(U)",
      id: 105,
      name: "AMD Ryzen 7",
      price: "299",
      stock: 45,
      visible: true,
    },
    {
      category: "Storage",
      desc: "Generic USB Drive 8GB",
      id: 115,
      name: "USB Drive 8GB",
      price: "30",
      stock: 123,
      visible: true,
    },
    {
      category: "Storage",
      desc: "No way you can still use this",
      id: 122,
      name: "Floppy Disc",
      price: "15",
      stock: 56,
      visible: true,
    },
    {
      category: "Peripherals",
      desc: "The fanciest keyboard youve ever seen!",
      id: 147,
      name: "Keyboard",
      price: "1999.99",
      stock: 0,
      visible: true,
    },
    {
      category: "PC",
      desc: "Its good for gaming",
      id: 106,
      name: "AMD Ryzen 5",
      price: "199",
      stock: 978,
      visible: true,
    },
    {
      category: "Storage",
      desc: "Generic USB Drive 1GB",
      id: 118,
      name: "USB Drive 1GB",
      price: "20",
      stock: 74,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 140,
      name: "Lowes",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 139,
      name: "Best Buy",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 138,
      name: "Neopets",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 137,
      name: "Walgreens",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 142,
      name: "VISA",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Storage",
      desc: "A Samsung SSD with 1TB capacity",
      id: 119,
      name: "Samsung SSD 1TB",
      price: "100",
      stock: 135,
      visible: true,
    },
    {
      category: "Storage",
      desc: "Generic USB Drive 60GB",
      id: 120,
      name: "USB Drive 60GB",
      price: "50",
      stock: 129,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 141,
      name: "Apple",
      price: "25",
      stock: 2670,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "They call me Houdini",
      id: 114,
      name: "Product1",
      price: "0.02",
      stock: 0,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "They call me Houdini",
      id: 144,
      name: "Product1",
      price: "0.02",
      stock: 0,
      visible: true,
    },
    {
      category: "Storage",
      desc: "Surprised you still need this",
      id: 121,
      name: "CD",
      price: "10",
      stock: 617,
      visible: true,
    },
    {
      category: "Consoles",
      desc: "They call me Houdini",
      id: 151,
      name: "Prod1",
      price: "169.99",
      stock: 1,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 136,
      name: "Amazon",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 135,
      name: "Target",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 134,
      name: "Steam",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Gift Cards",
      desc: "Customizable value gift card",
      id: 133,
      name: "Gamestop",
      price: "25",
      stock: 150,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 129,
      name: "Bowser Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 132,
      name: "Rosalina Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 123,
      name: "Goomba Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 127,
      name: "Peach Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 124,
      name: "Steve Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Sharpest headset on the market now in red",
      id: 96,
      name: "Razer BlackShark V2 (Red)",
      price: "79.99",
      stock: 50,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Hypest headset in red",
      id: 93,
      name: "HyperX - Cloud Alpha (Red)",
      price: "80",
      stock: 15,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Hypest headset in silver",
      id: 94,
      name: "HyperX - Cloud Alpha (Silver)",
      price: "80",
      stock: 45,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Sharpest headset on the market now in blue",
      id: 98,
      name: "Razer BlackShark V2 (Blue)",
      price: "79.99",
      stock: 50,
      visible: true,
    },
    {
      category: "Audio",
      desc: "Sturdy audio",
      id: 95,
      name: "SteelSeries Arctis 7+",
      price: "55.00",
      stock: 43,
      visible: true,
    },
    {
      category: "PC",
      desc: "Good quality and good price",
      id: 110,
      name: "Intel Core i3",
      price: "199",
      stock: 481,
      visible: true,
    },
    {
      category: "PC",
      desc: "Good for work",
      id: 107,
      name: "AMD Ryzen 3",
      price: "99",
      stock: 472,
      visible: true,
    },
    {
      category: "PC",
      desc: "9 cores?",
      id: 111,
      name: "AMD Ryzen 9 ",
      price: "399",
      stock: 712,
      visible: true,
    },
    {
      category: "PC",
      desc: "Reliability and speed",
      id: 112,
      name: "Intel Core i7",
      price: "399",
      stock: 482,
      visible: true,
    },
    {
      category: "PC",
      desc: "Speed and good price",
      id: 109,
      name: "Intel Core i5",
      price: "299",
      stock: 62,
      visible: true,
    },
    {
      category: "PC",
      desc: "The most modern Intel CPU",
      id: 103,
      name: "Intel Core i9",
      price: "499",
      stock: 654,
      visible: true,
    },
    {
      category: "PC",
      desc: "The best in the market ",
      id: 108,
      name: "AMD Ryzen Threadripper",
      price: "499",
      stock: 460,
      visible: true,
    },
    {
      category: "PC",
      desc: "I guess they still make these",
      id: 104,
      name: "Intel Pentium",
      price: "50",
      stock: 630,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 131,
      name: "Shyguy Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 130,
      name: "Master Chief Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 128,
      name: "KK Slider Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
    {
      category: "Collectibles",
      desc: "Nintendo's most desired statuettes",
      id: 125,
      name: "Mario Amiibo",
      price: "29.99",
      stock: 30,
      visible: true,
    },
  ],
};

const accountStats = {
  Orders: [
    {
      order_id: 115,
      order_total: "375",
      products_ordered: [
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          name: "Apple",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Mon, 18 Apr 2022 03:13:03 GMT",
      total_product_quantity: 15,
      user_id: 187,
    },
    {
      order_id: 118,
      order_total: "375",
      products_ordered: [
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          name: "Apple",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Wed, 11 May 2022 21:00:56 GMT",
      total_product_quantity: 15,
      user_id: 187,
    },
    {
      order_id: 127,
      order_total: "375",
      products_ordered: [
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          name: "Apple",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Sat, 14 May 2022 16:35:03 GMT",
      total_product_quantity: 15,
      user_id: 187,
    },
    {
      order_id: 128,
      order_total: "375",
      products_ordered: [
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          name: "Apple",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Sat, 14 May 2022 19:20:11 GMT",
      total_product_quantity: 15,
      user_id: 187,
    },
    {
      order_id: 132,
      order_total: "10",
      products_ordered: [
        {
          category: "Storage",
          desc: "Surprised you still need this",
          name: "CD",
          price_sold: "10",
          quantity_bought: 1,
        },
      ],
      time_of_order: "Sun, 15 May 2022 06:30:53 GMT",
      total_product_quantity: 1,
      user_id: 190,
    },
    {
      order_id: 138,
      order_total: "375",
      products_ordered: [
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          name: "USB Drive 1GB",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Sun, 15 May 2022 06:55:44 GMT",
      total_product_quantity: 15,
      user_id: 193,
    },
    {
      order_id: 141,
      order_total: "750",
      products_ordered: [
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          name: "USB Drive 1GB",
          price_sold: "25",
          quantity_bought: 15,
        },
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          name: "USB Drive 1GB",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Thu, 19 May 2022 00:48:51 GMT",
      total_product_quantity: 30,
      user_id: 193,
    },
    {
      order_id: 142,
      order_total: "400",
      products_ordered: [
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          name: "PlayStation 4",
          price_sold: "25",
          quantity_bought: 1,
        },
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          name: "USB Drive 1GB",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Thu, 19 May 2022 00:49:18 GMT",
      total_product_quantity: 16,
      user_id: 193,
    },
    {
      order_id: 143,
      order_total: "3277.92",
      products_ordered: [
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          name: "PlayStation 4",
          price_sold: "359.99",
          quantity_bought: 8,
        },
        {
          category: "PC",
          desc: "Its good for gaming",
          name: "AMD Ryzen 5",
          price_sold: "199",
          quantity_bought: 2,
        },
      ],
      time_of_order: "Sun, 22 May 2022 16:50:34 GMT",
      total_product_quantity: 10,
      user_id: 213,
    },
    {
      order_id: 144,
      order_total: "375",
      products_ordered: [
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          name: "USB Drive 1GB",
          price_sold: "25",
          quantity_bought: 15,
        },
      ],
      time_of_order: "Sun, 22 May 2022 16:52:41 GMT",
      total_product_quantity: 15,
      user_id: 193,
    },
  ],
  "User Statistics": [
    {
      "Most Bought Categories": [
        {
          name: "Storage",
          quantity_bought: 76,
        },
        {
          name: "Gift Cards",
          quantity_bought: 60,
        },
        {
          name: "Consoles",
          quantity_bought: 9,
        },
        {
          name: "PC",
          quantity_bought: 2,
        },
      ],
    },
    {
      "Most Bought Products": [
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          id: 118,
          name: "USB Drive 1GB",
          price: "20",
          stock: 74,
          visible: true,
        },
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          id: 141,
          name: "Apple",
          price: "25",
          stock: 2670,
          visible: true,
        },
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          id: 39,
          name: "PlayStation 4",
          price: "359.99",
          stock: 25,
          visible: true,
        },
        {
          category: "PC",
          desc: "Its good for gaming",
          id: 106,
          name: "AMD Ryzen 5",
          price: "199",
          stock: 978,
          visible: true,
        },
        {
          category: "Storage",
          desc: "Surprised you still need this",
          id: 121,
          name: "CD",
          price: "10",
          stock: 617,
          visible: true,
        },
      ],
    },
    {
      "Cheapest Bought Products": [
        {
          category: "Storage",
          desc: "Surprised you still need this",
          id: 121,
          name: "CD",
          price: "10",
          stock: 617,
          visible: true,
        },
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          id: 39,
          name: "PlayStation 4",
          price: "359.99",
          stock: 25,
          visible: true,
        },
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          id: 141,
          name: "Apple",
          price: "25",
          stock: 2670,
          visible: true,
        },
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          id: 118,
          name: "USB Drive 1GB",
          price: "20",
          stock: 74,
          visible: true,
        },
        {
          category: "PC",
          desc: "Its good for gaming",
          id: 106,
          name: "AMD Ryzen 5",
          price: "199",
          stock: 978,
          visible: true,
        },
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          id: 39,
          name: "PlayStation 4",
          price: "359.99",
          stock: 25,
          visible: true,
        },
      ],
    },
    {
      "Most Expensive Bought Products": [
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          id: 39,
          name: "PlayStation 4",
          price: "359.99",
          stock: 25,
          visible: true,
        },
        {
          category: "PC",
          desc: "Its good for gaming",
          id: 106,
          name: "AMD Ryzen 5",
          price: "199",
          stock: 978,
          visible: true,
        },
        {
          category: "Consoles",
          desc: "PlayStation 4 Console. Have fun and explore a world of possibilities!",
          id: 39,
          name: "PlayStation 4",
          price: "359.99",
          stock: 25,
          visible: true,
        },
        {
          category: "Gift Cards",
          desc: "Customizable value gift card",
          id: 141,
          name: "Apple",
          price: "25",
          stock: 2670,
          visible: true,
        },
        {
          category: "Storage",
          desc: "Generic USB Drive 1GB",
          id: 118,
          name: "USB Drive 1GB",
          price: "20",
          stock: 74,
          visible: true,
        },
        {
          category: "Storage",
          desc: "Surprised you still need this",
          id: 121,
          name: "CD",
          price: "10",
          stock: 617,
          visible: true,
        },
      ],
    },
  ],
};

function StatsPage() {
  return (
    <div className="stats-body">
      <Grid celled="internally">
        <Grid.Column width={8}>
          <h1>Global</h1>
          <Grid>
            <Grid.Row>
              <HottestStats details={globalStats} />
            </Grid.Row>
            <Grid.Row>
              <CheapestnMostExpensiveProducts details={globalStats}/>
            </Grid.Row>
            <Grid.Row>
              <MostLikedProducts details={[globalStats, accountStats]} />
            </Grid.Row>
          </Grid>
        </Grid.Column>
        <Grid.Column width={8}>
          <h1>Personal</h1>
          <Grid>
            <Grid.Row>
              <MostBought />
            </Grid.Row>
            <Grid.Row>
              <CheapestnMostExpensiveProductsPersonal
                details={accountStats}
              />
            </Grid.Row>
          </Grid>
        </Grid.Column>
      </Grid>
    </div>
  );
}

export default StatsPage;
